kind: pipeline
name: node10

steps:
  - name: test
    image: node:10-slim
    commands:
      - yarn
      - yarn test
  - name: docker
    image: plugins/docker
    settings:
      repo: docker-registry.35.202.15.36.nip.io/graphql-backend
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      auto_tag_suffix: linux-amd64
