---
resources:
- name: source-code
  type: git
  source:
    branch: master
    uri: https://github.com/erkanzileli/graphql-backend

- name: graphql-backend
  type: docker-image
  source:
    repository: 192.168.1.6:5000/grapql-backend
    tag: "latest"
    insecure_registries: [ "http://192.168.1.6:5000" ]

jobs:
- name: build-image
  plan:
  - get: source-code
    trigger: true
  - put: graphql-backend
    params:
      build: source-code
      skip_download: true    

  # - task: do-your-task-here
  #   config:
  #     platform: linux
  #     image_resource:
  #       type: docker-image
  #       source:
  #         repository: ubuntu
  #     run:
  #       path: bash
  #       args:
  #       - -exc
  #       - |
  #         du -s -h