apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: graphql-backend
  name: graphql-backend
  labels:
    app: graphql-backend
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      namespace: graphql-backend
      labels:
        app: graphql-backend
    spec:
      containers:
        - name: graphql-backend
          image: 192.168.1.6:5000/graphql-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
