resource_types:
  - name: helm
    type: docker-image
    source:
      repository: linkyard/concourse-helm-resource

resources:
  - name: source-code
    type: git
    source:
      branch: master
      uri: https://github.com/erkanzileli/graphql-backend

  - name: app-image
    type: docker-image
    source:
      repository: docker-registry.35.202.15.36.nip.io/grapql-backend
      tag: "latest"
      username: "admin"
      password: "123qweasd"

  - name: helm
    type: helm
    source:
      cluster_ca: "((cluster-ca.ca))"
      cluster_url: https://35.238.121.65
      repos:
        - name: chartmuseum
          url: http://chartmuseum.35.202.15.36.nip.io
      token: ((admin-user-token.token))

jobs:
  - name: "build & push-registry"
    plan:
      - get: source-code
        trigger: true
      - put: app-image
        params:
          build: source-code
        get_params:
          skip_download: true
  - name: deploy
    plan:
      - get: app-image
        passed:
          - "build & push-registry"
        trigger: true
        params:
          save: true
      - task: master-digest
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: concourse/buildroot
              tag: git
          run:
            path: sh
            args:
              - -exc
              - |
                cat app-image/digest > ./app-digest/sha
          inputs:
            - name: app-image
          outputs:
            - name: app-digest
      - put: helm
        params:
          chart: chartmuseum/graphql-backend
          namespace: chartmuseum
          override_values:
            - key: registry.server
              value: docker-registry.35.202.15.36.nip.io
            - key: registry.username
              value: admin
            - key: registry.password
              value: 123qweasd
            - key: domain
              value: chartmuseum.35.202.15.36.nip.io
            - key: imagePullPolicy
              value: Always
            - key: image.digest
              path: app-image/digest
          release: graphql-backend
  # - task: do-your-task-here
  #   config:
  #     platform: linux
  #     image_resource:
  #       type: docker-image
  #       source:
  #         repository: ubuntu
  #     run:
  #       path: bash
  #       args:
  #       - -exc
  #       - |
  #         du -s -h
